% fMRI Artefact removal and Sleep Scoring Toolbox, aka. FASST
% Version 2 (FASST.2) 30-September-2011
%__________________________________________________________________________
%     ________  _____________ ___ 
%    / __ _/  |/ ___/_/_  __/|__ \
%   / /_ / /| |\__ \ \ / /   __/ /
%  / __// ___ |__/ / // / _ / __/ 
% /_/  /_/  |_|___/_//_/ (_)____/ 
%
% fMRI Artefact removal and Sleep Scoring Toolbox, FASST.2
% http://www.montefiore.ulg.ac.be/~phillips/FASST.html
%
%__________________________________________________________________________
%
% This Contents.m file holds the version ID for this release of FASST.
%
% FASST is written for MATLAB 7.5 (R2007b) onwards.
% Since there are no compiled files, FASST should work on any platform.
% Be aware that FASST works as an add-on to the SPM8 package:
% <http://www.fil.ion.ucl.ac.uk/spm>
%
% This version of FASST is compatible with SPM8, and uses a few routines
% from 3 other toolboxes:
% - EEGLAB, <http://sccn.ucsd.edu/eeglab/>
% - "The FMRIB Plug-in for EEGLAB",
%   <http://users.fmrib.ox.ac.uk/~rami/fmribplugin/>
% - the "Mutual Information computation" package,
%   <http://penglab.janelia.org/proj/mRMR/>
%
% fMRI Artefact removal and Sleep Scoring Toolbox, FASST, is a set of tools
% to handle (long) continuous M/EEG data files. More specifically FASST was
% designed 
% - to remove from EEG data recorded during fMRI acquisition the artefacts 
%   generated by the functioning MR scanner and its intense static field;
% - to help the manual scoring of sleep recordings, and the review of this
%   scoring.
% These tools could find other applications invovling the analysis and 
% display of signal continuous recordings.
%
% FASST is  developed by the "methods team" of the Cyclotron Research
% Centre at the University of Liege (ULg), Belgium.
%
% The development of FASST was possible with the financial support of 
% - the Fonds de la Recherche Scientifique-FNRS, 
% - the Queen Elizabeth's fund, and
% - the University of Liege.
%
% FASST is free software: you can redistribute it  and/or modify it under 
% the terms of the GNU General Public License as published by the Free 
% Software Foundation,  either version 2 of  the License,  or (at  your 
% option) any later version.
% FASST is  distributed in the hope  that it will be  useful, but WITHOUT 
% ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or 
% FITNESS FOR A  PARTICULAR PURPOSE.  See the  GNU General Public License 
% for more  details.
% You should  have received a copy of the  GNU General Public License along
% with FASST, in crc_LICENCE.man. If not, see 
% <http://www.gnu.org/licenses/>.
%__________________________________________________________________
% Copyright (C) 2010 Cyclotron Research Centre

% Written by J. Schrouff, Y. Leclercq & C. Phillips, 2010.
% Cyclotron Research Centre, University of Liege, Belgium
% $Id$

% list of files
% - in the main directory
%       CRC_electrodes.mat
%       Contents.m
%       FASST_manual.bib
%       FASST_manual.pdf
%       FASST_manual.tex
%       LOGO_Simple.png
%       crc_CreateSV.m
%       crc_DrawSV.m
%       crc_LICENCE.man
%       crc_SP_detect.m
%       crc_SP_detection.fig
%       crc_SP_detection.m
%       crc_SWS_detect.m
%       crc_SWS_mapping.m
%       crc_append_spm.m
%       crc_batch.m
%       crc_cfg_chunk.m
%       crc_cfg_fasst.m
%       crc_cfg_feedback.m
%       crc_cfg_gar.m
%       crc_cfg_par.m
%       crc_cfg_rdata_brpr.m
%       crc_cfg_sws.m
%       crc_check_flag.m
%       crc_chunks.fig
%       crc_chunks.m
%       crc_concatenate.m
%       crc_cont2epoch.m
%       crc_defaults.m
%       crc_dis_main.fig
%       crc_dis_main.m
%       crc_dsample.m
%       crc_eeg_load.m
%       crc_eeg_rdata_brpr.m
%       crc_eeg_rdata_edf.m
%       crc_eeg_rdata_egi.m
%       crc_eeg_readHeaderBrainP.m
%       crc_eeg_readHeaderEGI.m
%       crc_eeg_readHeaderEDF.m
%       crc_elecpos_sph.m
%       crc_electrodes.m
%       crc_export_files.m
%       crc_extractSW.m
%       crc_freqappnd_spm.m
%       crc_freqsave_spm.m
%       crc_gar.m
%       crc_get_defaults.m
%       crc_main.fig
%       crc_main.m
%       crc_par.m
%       crc_par_aas.m
%       crc_par_aaspca.m
%       crc_par_cICA.m
%       crc_par_cICAmx.m
%       crc_par_cICAqa.m
%       crc_par_cICAsav.m
%       crc_par_cica.asv
%       crc_par_iica.m
%       crc_par_pca.m
%       crc_par_selchan.fig
%       crc_par_selchan.m
%       crc_percentile.m
%       crc_plothypno.asv
%       crc_plothypno.m
%       crc_process_chunk.m
%       crc_run_chunking.m
%       crc_run_feedback.m
%       crc_save_spm.m
%       crc_scales.m
%       crc_set_hourdate.m
%       crc_spectcompute.m
%       crc_spm5tospm8.m
%       crc_statgen.m
%       crc_sws_detection.fig
%       crc_sws_detection.m
%       crc_time_converts.m
%       crc_wave_detection.fig
%       crc_wave_detection.m
%       dis_SWS_selchan.fig
%       dis_SWS_selchan.m
%       dis_cICAcheck.fig
%       dis_cICAcheck.m
%       dis_frq.fig
%       dis_frq.m
%       dis_frqcomp.fig
%       dis_frqcomp.m
%       dis_selchan.fig
%       dis_selchan.m
%       fasst.m
%       fmrib_pas.m
%       fmrib_qrsdetect.m
%       pcamat.m
%       qrscorrect.m
%       whitenv.m
% - in the 'images' subdirectory
%       FIG10_crc_chunk.jpg
%       FIG12_score_stats.jpg
%       FIG13_wave_detection.JPG
%       FIG14_SWS_gui.JPG
%       FIG15_SWS_ROI_sel.JPG
%       FIG16_SWS_criteria.jpg
%       FIG17_SP_datarms.fig
%       FIG17_dis_SW.jpg
%       FIG18_SP_datarms.jpg
%       FIG19_SP_gui.JPG
%       FIG1_crc_main.JPG
%       FIG20_dis_SP_detect.jpg
%       FIG2_dis_selchan.jpg
%       FIG3-TB_dismainpwr.jpg
%       FIG3_crc_dis.jpg
%       FIG4_dis_pwr.jpg
%       FIG5_dis_cmp.jpg
%       FIG6_spect_cmp.jpg
%       FIG7_disfreq_spectro.jpg
%       FIG8_disfreq_fband.jpg
%       FIG9_disfreq_pwrstage.jpg
%       Fig11_dis_score.jpg
%       LOGO_Complex.png
%       LOGO_Simple.png
% - in the 'SPTfunctions' subdirectory
%       butter
%       filtfilt
%       pwelch
% - in the 'MInfo' subdirectoy
% see http://penglab.janelia.org/proj/mRMR/